# Generated by Django 5.2.7 on 2025-12-31 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerfumeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfume_name', models.CharField(choices=[('純白の物語', '純白の物語'), ('夜明けの読書', '夜明けの読書'), ('秘密の書斎', '秘密の書斎'), ('雨の図書室', '雨の図書室'), ('月夜の詩集', '月夜の詩集'), ('湖畔の画集', '湖畔の画集'), ('恋の序章', '恋의序章'), ('夕暮れの物語', '夕暮れの物語'), ('葡萄色の日記', '葡萄色の日記'), ('飴色の文学', '飴色の文学')], max_length=100, verbose_name='香水名')),
                ('content', models.TextField(verbose_name='香りの感想')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
